//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheapMarket.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringRecursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringRecursos() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheapMarket.Recursos.StringRecursos", typeof(StringRecursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        internal static string Administración {
            get {
                return ResourceManager.GetString("Administración", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AGREGAR.
        /// </summary>
        internal static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Añadir producto.
        /// </summary>
        internal static string Añadir_producto {
            get {
                return ResourceManager.GetString("Añadir_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        internal static string Apellidos {
            get {
                return ResourceManager.GetString("Apellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BEBIDAS.
        /// </summary>
        internal static string Bebidas {
            get {
                return ResourceManager.GetString("Bebidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido a Cheap Market.
        /// </summary>
        internal static string Bienvenido_a_Cheap_Market {
            get {
                return ResourceManager.GetString("Bienvenido_a_Cheap_Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADMIN.
        /// </summary>
        internal static string btn_Admin {
            get {
                return ResourceManager.GetString("btn_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENTRAR.
        /// </summary>
        internal static string btn_Entrar {
            get {
                return ResourceManager.GetString("btn_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGÍSTRATE.
        /// </summary>
        internal static string btn_Registrate {
            get {
                return ResourceManager.GetString("btn_Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Canjear.
        /// </summary>
        internal static string Canjear {
            get {
                return ResourceManager.GetString("Canjear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad.
        /// </summary>
        internal static string Cantidad {
            get {
                return ResourceManager.GetString("Cantidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad a eliminar:.
        /// </summary>
        internal static string Cantidad_a_eliminar {
            get {
                return ResourceManager.GetString("Cantidad_a_eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar Imagen.
        /// </summary>
        internal static string Cargar_imagen {
            get {
                return ResourceManager.GetString("Cargar_imagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CARNICERÍA.
        /// </summary>
        internal static string Carnicería {
            get {
                return ResourceManager.GetString("Carnicería", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría:.
        /// </summary>
        internal static string Categoría {
            get {
                return ResourceManager.GetString("Categoría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CERRAR SESIÓN.
        /// </summary>
        internal static string Cerrar_sesion {
            get {
                return ResourceManager.GetString("Cerrar_sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5€ descuento:.
        /// </summary>
        internal static string cincoeuros_descuento {
            get {
                return ResourceManager.GetString("cincoeuros_descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código:.
        /// </summary>
        internal static string Código {
            get {
                return ResourceManager.GetString("Código", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código Postal.
        /// </summary>
        internal static string Codigo_Postal {
            get {
                return ResourceManager.GetString("Codigo_Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a COMIDAS PREP..
        /// </summary>
        internal static string Comidas_Preparadas {
            get {
                return ResourceManager.GetString("Comidas_Preparadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo Electrónico.
        /// </summary>
        internal static string Correo_Electrónico {
            get {
                return ResourceManager.GetString("Correo_Electrónico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4000 puntos.
        /// </summary>
        internal static string cuatromil_puntos {
            get {
                return ResourceManager.GetString("cuatromil_puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Personales.
        /// </summary>
        internal static string Datos_Personales {
            get {
                return ResourceManager.GetString("Datos_Personales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción:.
        /// </summary>
        internal static string Descripción {
            get {
                return ResourceManager.GetString("Descripción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 10% descuento:.
        /// </summary>
        internal static string diezporciento_descuento {
            get {
                return ResourceManager.GetString("diezporciento_descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        internal static string Direccion {
            get {
                return ResourceManager.GetString("Direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Entrega.
        /// </summary>
        internal static string Direccion_entrega {
            get {
                return ResourceManager.GetString("Direccion_entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doble click en un producto para eliminar.
        /// </summary>
        internal static string Doble_click_en_un_producto {
            get {
                return ResourceManager.GetString("Doble_click_en_un_producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2500 puntos.
        /// </summary>
        internal static string dosmilquinientos_puntos {
            get {
                return ResourceManager.GetString("dosmilquinientos_puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR PRODUCTO.
        /// </summary>
        internal static string Editar_Producto {
            get {
                return ResourceManager.GetString("Editar_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIGE METODO DE PAGO.
        /// </summary>
        internal static string ELIGE_METODO_DE_PAGO {
            get {
                return ResourceManager.GetString("ELIGE_METODO_DE_PAGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar filtros.
        /// </summary>
        internal static string Eliminar_filtros {
            get {
                return ResourceManager.GetString("Eliminar_filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ELIMINAR PRODUCTO.
        /// </summary>
        internal static string Eliminar_Producto {
            get {
                return ResourceManager.GetString("Eliminar_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Producto.
        /// </summary>
        internal static string Eliminar_ProductoMin {
            get {
                return ResourceManager.GetString("Eliminar_ProductoMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como invitado.
        /// </summary>
        internal static string Entrar_como_invitado {
            get {
                return ResourceManager.GetString("Entrar_como_invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío Gratis:.
        /// </summary>
        internal static string Envío_Gratis {
            get {
                return ResourceManager.GetString("Envío_Gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Eres nuevo?.
        /// </summary>
        internal static string Eres_nuevo {
            get {
                return ResourceManager.GetString("Eres_nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FIAMBRES.
        /// </summary>
        internal static string Fiambres {
            get {
                return ResourceManager.GetString("Fiambres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtrar.
        /// </summary>
        internal static string Filtrar {
            get {
                return ResourceManager.GetString("Filtrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtros:.
        /// </summary>
        internal static string Filtros_dospuntitos {
            get {
                return ResourceManager.GetString("Filtros_dospuntitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FINALIZAR COMPRA.
        /// </summary>
        internal static string FINALIZAR_COMPRA {
            get {
                return ResourceManager.GetString("FINALIZAR_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FINALIZAR PEDIDO.
        /// </summary>
        internal static string FINALIZAR_PEDIDO {
            get {
                return ResourceManager.GetString("FINALIZAR_PEDIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FRUTERÍA.
        /// </summary>
        internal static string Frutería {
            get {
                return ResourceManager.GetString("Frutería", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GUARDAR CAMBIOS.
        /// </summary>
        internal static string Guardar_cambios {
            get {
                return ResourceManager.GetString("Guardar_cambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a He leído y acepto los términos y condiciones de uso.
        /// </summary>
        internal static string He_leido_y_acepto_los_terminos {
            get {
                return ResourceManager.GetString("He_leido_y_acepto_los_terminos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HELADOS.
        /// </summary>
        internal static string Helados {
            get {
                return ResourceManager.GetString("Helados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HIGIENE.
        /// </summary>
        internal static string Higiene {
            get {
                return ResourceManager.GetString("Higiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HOGAR.
        /// </summary>
        internal static string Hogar {
            get {
                return ResourceManager.GetString("Hogar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información nutricional.
        /// </summary>
        internal static string Informacion_Nutricional {
            get {
                return ResourceManager.GetString("Informacion_Nutricional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información nutritiva.
        /// </summary>
        internal static string Información_nutritiva {
            get {
                return ResourceManager.GetString("Información_nutritiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insertar.
        /// </summary>
        internal static string Insertar {
            get {
                return ResourceManager.GetString("Insertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERTAR PRODUCTO.
        /// </summary>
        internal static string Insertar_Producto {
            get {
                return ResourceManager.GetString("Insertar_Producto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado.
        /// </summary>
        internal static string Invitado {
            get {
                return ResourceManager.GetString("Invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LISTA.
        /// </summary>
        internal static string Lista {
            get {
                return ResourceManager.GetString("Lista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        internal static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1700 puntos.
        /// </summary>
        internal static string milsetecientos_puntos {
            get {
                return ResourceManager.GetString("milsetecientos_puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string Nombre_dospuntitos {
            get {
                return ResourceManager.GetString("Nombre_dospuntitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Num/Piso/Puerta.
        /// </summary>
        internal static string Num_Piso_Puerta {
            get {
                return ResourceManager.GetString("Num_Piso_Puerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PANADERÍA.
        /// </summary>
        internal static string Panadería {
            get {
                return ResourceManager.GetString("Panadería", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PESCADERÍA.
        /// </summary>
        internal static string Pescadería {
            get {
                return ResourceManager.GetString("Pescadería", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Promociones:.
        /// </summary>
        internal static string Promociones {
            get {
                return ResourceManager.GetString("Promociones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        internal static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        internal static string Puntos {
            get {
                return ResourceManager.GetString("Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Quiero que me envien publicidad por correo electrónico!.
        /// </summary>
        internal static string Quiero_que_me_envien {
            get {
                return ResourceManager.GetString("Quiero_que_me_envien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REALIZAR COMPRA.
        /// </summary>
        internal static string REALIZAR_COMPRA {
            get {
                return ResourceManager.GetString("REALIZAR_COMPRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REGÍSTRATE.
        /// </summary>
        internal static string REGISTRATE {
            get {
                return ResourceManager.GetString("REGISTRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repetir Contraseña.
        /// </summary>
        internal static string Repetir_Contraseña {
            get {
                return ResourceManager.GetString("Repetir_Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SNACKS.
        /// </summary>
        internal static string Snacks {
            get {
                return ResourceManager.GetString("Snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Supermercado.
        /// </summary>
        internal static string Supermercado {
            get {
                return ResourceManager.GetString("Supermercado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TARJETA DE CRÉDITO.
        /// </summary>
        internal static string TARJETA_DE_CREDITO {
            get {
                return ResourceManager.GetString("TARJETA_DE_CREDITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string Telefono {
            get {
                return ResourceManager.GetString("Telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Tienes dudas? ¡Llámanos!.
        /// </summary>
        internal static string Tienes_dudas_Llamanos {
            get {
                return ResourceManager.GetString("Tienes_dudas_Llamanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total:.
        /// </summary>
        internal static string Total_dospuntos {
            get {
                return ResourceManager.GetString("Total_dospuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VACIAR CARRITO.
        /// </summary>
        internal static string VACIAR_CARRITO {
            get {
                return ResourceManager.GetString("VACIAR_CARRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VERDULERÍA.
        /// </summary>
        internal static string Verdulería {
            get {
                return ResourceManager.GetString("Verdulería", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VOLVER A INICIO.
        /// </summary>
        internal static string VOLVER_A_INICIO {
            get {
                return ResourceManager.GetString("VOLVER_A_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y consigue 100 puntos gratis en tu primera compra.
        /// </summary>
        internal static string Y_consigue_100_puntos_gratis {
            get {
                return ResourceManager.GetString("Y_consigue_100_puntos_gratis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes cuenta?.
        /// </summary>
        internal static string Ya_tienes_cuenta {
            get {
                return ResourceManager.GetString("Ya_tienes_cuenta", resourceCulture);
            }
        }
    }
}
